"""Generate a joke using the Llama 3.3 70B model hosted on Groq."""

from config import get_groq_client

JOKE_MODEL = "llama-3.3-70b-versatile"


def get_joke() -> str:
    """Return a joke generated by Llama 3.3 via the Groq API.

    Returns:
        The text of the assistant's reply.
    """

    client = get_groq_client()
    response = client.chat.completions.create(
        model=JOKE_MODEL,
        messages=[
            {"role": "system", "content": "You are a funny joke teller."},
            {"role": "user", "content": "Tell me a joke."},
        ],
    )
    return response.choices[0].message.content


if __name__ == "__main__":
    print(get_joke())
