"""Generate a joke using the Llama 3.3 70B model hosted on Groq."""

import random
from config import get_groq_client

JOKE_MODEL = "llama-3.3-70b-versatile"

def get_joke(topic: str = "") -> str:
    """Return a joke generated by Llama 3.3 via the Groq API.

    Args:
        topic: Optional topic or category requested by the user.
               If empty, a random category is chosen.

    Returns:
        The text of the assistant's reply.
    """

    subject = topic.strip() if topic.strip() else "random"
    client = get_groq_client()
    response = client.chat.completions.create(
        model=JOKE_MODEL,
        temperature=1.3,
        messages=[
            {"role": "system", "content": "You are a comedian with a huge repertoire of jokes. Never repeat the same joke twice."},
            {"role": "user", "content": f"Tell me a joke about {subject}. Just the joke, no commentary."},
        ],
    )
    return response.choices[0].message.content


if __name__ == "__main__":
    print(get_joke())
