services:
  web:
    build: .
    env_file: .env
    command: python src/app.py
    ports:
      - "8080:5000"
    volumes:
      - ./src:/app/src

  joke:
    build: .
    env_file: .env
    command: python src/joke.py

  travel:
    build: .
    env_file: .env
    command: python src/travel.py

  summarize:
    build: .
    env_file: .env
    command: python src/summarizer.py

  arena:
    build: .
    env_file: .env
    command: python src/arena.py
