services:
  web:
    build: .
    env_file: .env
    command: python src/app.py
    ports:
      - "8081:5000"
    volumes:
      - ./src:/app/src

  summarize:
    build: .
    env_file: .env
    command: python src/summarizer.py

  chat:
    build: .
    env_file: .env
    command: python src/chat.py

  agent:
    build: .
    env_file: .env
    command: python src/agent.py
