"""Flask server exposing joke, travel, summarize, and arena endpoints.

Architecture notes
------------------
- All routes are attached to a Blueprint (``bp``) instead of directly to
  ``app``.  This lets us register the entire Blueprint under a runtime
  URL prefix (``PATH_PREFIX``) without touching individual route strings.
- In local development PATH_PREFIX is empty, so routes are at "/", "/joke",
  etc.  In production Nginx forwards ``/basic/...`` traffic to the container
  and PATH_PREFIX is set to "/basic", keeping every URL consistent.
- flask-cors adds ``Access-Control-Allow-Origin: *`` headers so the HTML
  page can call the API even if it is served from a different origin during
  development.
"""

import os
from pathlib import Path

from flask import Blueprint, Flask, jsonify, request
from flask_cors import CORS

from arena import battle
from joke import get_joke
from rate_limiter import check_rate_limit
from summarizer import MAX_TEXT_CHARS, PERSONALITIES, summarize, summarize_text
from travel import get_travel_suggestion

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# PATH_PREFIX is set by the deployment environment (e.g. "/basic") so the app
# works correctly behind an Nginx location block.  Locally it is empty string,
# which mounts all routes at the root.
PATH_PREFIX = os.environ.get("PATH_PREFIX", "")

# app.py lives in src/python, while index.html, css/, and js/ live in src/.
STATIC_DIR = Path(__file__).resolve().parents[1]
app = Flask(__name__, static_folder=str(STATIC_DIR))

# Allow cross-origin requests from any origin.  In production you would
# restrict this to the specific front-end domain.
CORS(app)

# A Blueprint groups related routes.  We register it once at the bottom with
# the runtime PATH_PREFIX, avoiding any hardcoded path strings in the routes.
bp = Blueprint("main", __name__)


@bp.before_request
def enforce_rate_limit():
    """Enforce strict 10 requests per hour limit on all POST endpoints."""
    # ① only rate-limit POST requests because static pages are safe to serve
    if request.method == "POST":
        # ② ask the shared limiter whether this client has exceeded the window
        blocked, msg, retry_after = check_rate_limit(
            request, max_requests=10, window_seconds=3600
        )
        # ③ return a 429 response when the limiter says the client is blocked
        if blocked:
            resp = jsonify({"error": msg})
            resp.status_code = 429
            resp.headers["Retry-After"] = str(retry_after)
            return resp


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@bp.route("/")
def index():
    """Serve index.html, injecting the correct API base URL for the environment."""
    # ① read the bundled HTML shell from the static source directory
    with open(os.path.join(app.static_folder, "index.html"), encoding="utf-8") as f:
        html = f.read()
    # ② inject the deployment path prefix so browser fetch calls hit the API
    # The HTML file ships with 'data-api-base=""' (empty = relative URL, works
    # locally).  For production we replace it with the actual path prefix so
    # all fetch() calls in the browser target the right endpoint.
    html = html.replace('data-api-base=""', f'data-api-base="{PATH_PREFIX}"')
    # ③ return the patched HTML with the correct content type
    return app.response_class(html, mimetype="text/html")


@bp.route("/css/<path:filename>")
def css(filename):
    """Serve stylesheets from the src/css directory."""
    return app.send_static_file(os.path.join("css", filename))


@bp.route("/js/<path:filename>")
def js(filename):
    """Serve scripts from the src/js directory."""
    return app.send_static_file(os.path.join("js", filename))


@bp.route("/info/<path:filename>")
def info(filename):
    """Serve the "how this demo works" explainer pages from src/info."""
    return app.send_static_file(os.path.join("info", filename))


@bp.route("/joke", methods=["POST"])
def joke():
    """Return a joke generated by GPT OSS 120B on Groq.

    Request body (JSON): ``{ "topic": "<optional topic>" }``
    Response (JSON):     ``{ "result": "<joke text>" }``
    Error response:      ``{ "error": "<message>" }`` with HTTP 500
    """
    # ① parse the JSON request body from the browser
    data = request.get_json(force=True)
    # ② normalize the optional topic so get_joke can choose random if empty
    # topic is optional; an empty string causes get_joke() to pick randomly.
    topic = (data.get("topic") or "").strip()
    try:
        # ③ generate the joke through the Groq-backed feature module
        text = get_joke(topic)
        # ④ wrap the joke in JSON and disable caching so each click is fresh
        response = jsonify({"result": text})
        # Prevent the browser from caching joke responses — every click
        # should fetch a fresh joke from the API.
        response.headers["Cache-Control"] = "no-store"
        return response
    # ⑤ convert unexpected model or API failures into a JSON error
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@bp.route("/travel", methods=["POST"])
def travel():
    """Return a travel suggestion for a city via GPT-4o mini.

    Request body (JSON): ``{ "city": "<city name>" }``
    Response (JSON):     ``{ "result": "<suggestion text>" }``
    Error response:      ``{ "error": "<message>" }`` with HTTP 500
    """
    # ① parse the JSON request body from the browser
    data = request.get_json(force=True)
    # ② choose the submitted city or a Bangalore default for empty input
    # Fall back to Bangalore if the user submits an empty city, so the
    # call to get_travel_suggestion() always has a usable value.
    city = (data.get("city") or "").strip() or "Bangalore"
    try:
        # ③ ask the travel feature module for one suggestion
        text = get_travel_suggestion(city)
        # ④ return the suggestion in the response shape the UI expects
        return jsonify({"result": text})
    # ⑤ convert unexpected model or API failures into a JSON error
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@bp.route("/summarize", methods=["POST"])
def summarizer():
    """Summarize a URL (scraped) or pasted article text with GPT-4o mini.

    Request body (JSON): ``{ "url": "<website URL>" }`` or
                         ``{ "text": "<article text>" }``, plus an optional
                         ``"personality"`` (friendly | snarky | eli5 | professional)
    Response (JSON):     ``{ "result": "<markdown summary>" }``
    Error response:      ``{ "error": "<message>" }`` with HTTP 400 (bad input)
                         or HTTP 500 (API / scraping error)
    """
    # ① parse the JSON request body from the browser
    data = request.get_json(force=True)
    # ② normalize URL, article text, and summary personality inputs
    url = (data.get("url") or "").strip()
    article = (data.get("text") or "").strip()
    personality = (data.get("personality") or "friendly").strip()
    # ③ validate at the boundary before spending scraper or model work
    # Validate at the boundary — return 400 immediately rather than letting
    # the scraper or model run on bad input.
    if not url and not article:
        return jsonify({"error": "A website URL or article text is required."}), 400
    if personality not in PERSONALITIES:
        return jsonify({"error": "Unknown personality."}), 400
    if len(article) > MAX_TEXT_CHARS:
        return jsonify({"error": f"Text is too long (max {MAX_TEXT_CHARS:,} characters)."}), 400
    try:
        # ④ summarize pasted text directly, otherwise scrape and summarize the URL
        text = summarize_text(article, personality) if article else summarize(url, personality)
        # ⑤ return the markdown summary in the response shape the UI expects
        return jsonify({"result": text})
    # ⑥ convert unexpected scraper or model failures into a JSON error
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@bp.route("/arena", methods=["POST"])
def arena():
    """Send one prompt to two models and return both responses.

    Request body (JSON): ``{ "prompt": "<user prompt>" }``
    Response (JSON)::

        {
          "result": {
            "model_a": {"model": "gpt-4o-mini",            "reply": "..."},
            "model_b": {"model": "openai/gpt-oss-120b", "reply": "..."}
          }
        }

    Error response: ``{ "error": "<message>" }`` with HTTP 400 (missing prompt)
                    or HTTP 500 (API error)
    """
    # ① parse the JSON request body from the browser
    data = request.get_json(force=True)
    # ② normalize the prompt before validating it
    prompt = (data.get("prompt") or "").strip()
    # ③ reject empty prompts before calling either model
    if not prompt:
        return jsonify({"error": "A prompt is required."}), 400
    try:
        # ④ send the prompt to both arena models for comparison
        result = battle(prompt)
        # ⑤ return both labelled model replies to the UI
        return jsonify({"result": result})
    # ⑥ convert unexpected model or API failures into a JSON error
    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ---------------------------------------------------------------------------
# Blueprint registration + server entry point
# ---------------------------------------------------------------------------

# Register all Blueprint routes under the optional path prefix.  This single
# line is the only place where PATH_PREFIX is applied — every route above is
# written as a relative path (e.g. "/joke") and the prefix is prepended here.
app.register_blueprint(bp, url_prefix=PATH_PREFIX)


if __name__ == "__main__":
    # Run the development server.  0.0.0.0 makes the app reachable from
    # outside the container; port 5000 is mapped to host port 8080 by
    # docker-compose.yml.
    app.run(host="0.0.0.0", port=5000)
