"""Generate a joke using the Llama 3.3 70B model hosted on Groq.

We use Groq here because it offers a very high inference speed (tokens/sec)
and a free tier, making it ideal for a low-latency interactive demo.
"""

import random
from config import get_groq_client

# Llama 3.3 70B Versatile is one of Groq's fastest hosted open-source models.
# The "versatile" variant is instruction-tuned and performs well on creative
# tasks like joke generation.
JOKE_MODEL = "openai/gpt-oss-120b"


def get_joke(topic: str = "") -> str:
    """Return a joke generated by Llama 3.3 via the Groq API.

    Args:
        topic: Optional topic or category requested by the user.
               If empty, the word "random" is passed so the model
               picks whatever it likes.

    Returns:
        The text of the assistant's reply — just the joke, no preamble.
    """
    # Fall back to "random" so the prompt is always explicit about what we want
    # rather than sending an empty string which could confuse the model.
    subject = topic.strip() if topic.strip() else "random"

    client = get_groq_client()
    response = client.chat.completions.create(
        model=JOKE_MODEL,
        # temperature controls randomness: 0 = deterministic, 2 = very random.
        # 1.3 is intentionally high so we get a fresh, creative joke every time
        # rather than the same few the model defaults to at lower temperatures.
        temperature=1.3,
        messages=[
            {
                "role": "system",
                # The system prompt defines the model's persona and ground rules.
                # Telling it never to repeat a joke nudges it toward variety.
                "content": "You are a comedian with a huge repertoire of jokes. Never repeat the same joke twice.",
            },
            {
                "role": "user",
                # The user prompt keeps it laser-focused: one joke, no wrapper text,
                # so we can display the result directly in the UI.
                "content": f"Tell me a joke about {subject}. Just the joke, no commentary.",
            },
        ],
    )
    # choices[0] is the first (and only) completion; .message.content is the
    # assistant's reply text.
    return response.choices[0].message.content


if __name__ == "__main__":
    # Quick manual test: run `python joke.py` to print a joke to the terminal.
    print(get_joke())
